/*
 * *******************************************************************************
 * Copyright (C) QuantActions AG - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * Written by Enea Ceolini <enea.ceolini@quantactions.com>, August 2024
 * *******************************************************************************
 */

buildscript {

    repositories {
        mavenCentral()
        maven {
            url = "https://plugins.gradle.org/m2/"
        }
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:2.0.0"
        classpath "org.jetbrains.dokka:dokka-gradle-plugin:2.0.0"
        classpath "org.jetbrains.dokka:android-documentation-plugin:2.0.0"
        classpath "org.jetbrains.kotlin:kotlin-serialization:2.2.10"
        classpath "org.jetbrains.kotlin:compose-compiler-gradle-plugin:2.2.10"
    }

    ext {
        customFooterMessage = "Made with ❤️ at QuantActions"
        customLogoFile = projectDir.toString() + "/logo-style.css"
    }

}

plugins {
    id 'com.google.devtools.ksp' version '2.2.10-2.0.2' apply false
    id 'com.google.dagger.hilt.android' version '2.57.2' apply false
}

allprojects {
    repositories {
        mavenCentral()
        google()
        maven {
            url = "https://plugins.gradle.org/m2/"
        }
    }
}
